# docker-compose.production.yml
version: '3'

volumes:
  pg_data:
  static:
  media:

# Всё отличие — заменяем build на image и указываем, какой образ использовать
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: alexmos2/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
  frontend:
    image: alexmos2/kittygram_frontend  # Качаем с Docker Hub
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: alexmos2/kittygram_gateway  # Качаем с Docker Hub
    env_file: .env
    volumes:
      - static:/staticfiles/
      - media:/media
    ports:
      - 9000:80
